In [7]:
import pandas as pd 

df = pd.read_csv('players_15.csv')

In [9]:
df.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,27,1987-06-24,169,67,Argentina,FC Barcelona,...,62+3,62+3,62+3,62+3,62+3,54+3,45+3,45+3,45+3,54+3
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,29,1985-02-05,185,80,Portugal,Real Madrid,...,63+3,63+3,63+3,63+3,63+3,57+3,52+3,52+3,52+3,57+3
2,9014,https://sofifa.com/player/9014/arjen-robben/15...,A. Robben,Arjen Robben,30,1984-01-23,180,80,Netherlands,FC Bayern München,...,64+3,64+3,64+3,64+3,64+3,55+3,46+3,46+3,46+3,55+3
3,41236,https://sofifa.com/player/41236/zlatan-ibrahim...,Z. Ibrahimović,Zlatan Ibrahimović,32,1981-10-03,195,95,Sweden,Paris Saint-Germain,...,61+3,65+3,65+3,65+3,61+3,56+3,55+3,55+3,55+3,56+3
4,167495,https://sofifa.com/player/167495/manuel-neuer/...,M. Neuer,Manuel Neuer,28,1986-03-27,193,92,Germany,FC Bayern München,...,36+3,40+3,40+3,40+3,36+3,36+3,38+3,38+3,38+3,36+3

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16155 entries, 0 to 16154
Columns: 106 entries, sofifa_id to rb
dtypes: float64(18), int64(44), object(44)
memory usage: 13.1+ MB

In [12]:
df.describe()

,sofifa_id,age,height_cm,weight_kg,league_rank,overall,potential,value_eur,wage_eur,international_reputation,...,mentality_penalties,mentality_composure,defending_marking,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes
count,16155.000000,16155.000000,16155.000000,16155.000000,15916.000000,16155.000000,16155.000000,1.615500e+04,16155.000000,16155.000000,...,16155.000000,0.0,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000
mean,189284.184525,24.776230,181.083627,75.474342,1.378424,63.830393,68.350108,1.060882e+06,13056.453110,1.122501,...,49.648344,NaN,45.009037,47.656639,45.885918,15.869514,15.511668,15.354875,15.504735,15.998514
std,39749.261554,4.625321,6.618974,6.891796,0.736796,7.169896,6.580610,2.819128e+06,23488.182571,0.396263,...,14.552244,NaN,17.915206,18.743105,18.145497,17.576799,16.414173,16.010498,16.585081,17.983209
min,2.000000,16.000000,155.000000,50.000000,1.000000,40.000000,40.000000,0.000000e+00,0.000000,1.000000,...,20.000000,NaN,20.000000,20.000000,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,178042.500000,21.000000,176.000000,70.000000,1.000000,59.000000,64.000000,1.200000e+05,2000.000000,1.000000,...,39.000000,NaN,25.000000,25.000000,25.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,200841.000000,24.000000,181.000000,75.000000,1.000000,64.000000,68.000000,3.500000e+05,5000.000000,1.000000,...,50.000000,NaN,46.000000,52.000000,49.000000,11.000000,11.000000,11.000000,10.000000,10.000000
75%,214346.000000,28.000000,186.000000,80.000000,2.000000,68.000000,73.000000,8.250000e+05,10000.000000,1.000000,...,61.000000,NaN,61.000000,64.000000,62.000000,13.000000,14.000000,13.000000,13.000000,13.000000
max,225562.000000,44.000000,204.000000,110.000000,4.000000,93.000000,95.000000,1.005000e+08,550000.000000,5.000000,...,95.000000,NaN,90.000000,91.000000,95.000000,88.000000,87.000000,92.000000,90.000000,90.000000